# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [  "$TRAVIS_PHP_VERSION" != "7.0" ]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer install --prefer-dist --no-interaction

  - |
    if [ $TRAVIS_PHP_VERSION = '7.0' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi

script:
  -  phpunit --configuration phpunit.xml.dist $PHPUNIT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.0' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

