# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.5
  - 5.6
  - 7.0

addons:
  mariadb: '10.0'

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

before_script:
  - composer install


script:
  -  phpunit --configuration phpunit.xml

notifications:
  email: false 
