# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.5
  - 5.6
  - 7.0

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

before_script:
  - phpenv config-rm xdebug.ini;
  - composer self-update
  - composer install --prefer-dist --no-interaction


script:
  -  phpunit --configuration phpunit.xml.dist

notifications:
  email: false 
